### ISSUE TITLE
reduce function doesn't take array

### ISSUE THREAD

**Issue by J-Weeks** [ga-wdi-boston/js-array-methods#6] opened 2016-01-26 14:49 UTC
self explanatory.

**Comment by jrhorn424** [comment] 2016-01-28 03:22
Line number and file?

**Comment by jrhorn424** [comment] 2016-01-28 03:25
I think you might have missed the fact that developers write their own versions of some array methods. We don't want them overriding Array.prototype, so they have to pass arrays they want to mutate.

> We'll explore and implement proxies for a variety of the JavaScript Array methods.

**Comment by laurenfazah** [comment] 2016-03-25 17:37
Should this be an open issue? @J-Weeks @jrhorn424

**Comment by gaand** [comment] 2016-03-25 19:19
@laurenfazah I think not.  But @J-Weeks should confirm

**Comment by jrhorn424** [comment] 2016-05-23 15:36
I believe this is a duplicate of #9

**Closed** 2016-05-23 17:58 UTC
Labels: duplicate, in progress

**Comment by gaand** [comment] 2016-05-23 20:55
I think it might have been the mirror of a duplicate. :-P.
